# Generated by Django 4.2.11 on 2024-05-20 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address2',
        ),
    ]
